//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public string Employeeid { get; set; }
        public System.DateTime Date { get; set; }
        public int Courseid { get; set; }
        public string Status { get; set; }
    
        public virtual Training Training { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
