//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int feedbackid { get; set; }
        public string Employeeid { get; set; }
        public string Description { get; set; }
        public int Courseid { get; set; }
        public Nullable<int> Question1 { get; set; }
        public Nullable<int> Question2 { get; set; }
        public Nullable<int> Question3 { get; set; }
        public Nullable<int> Question4 { get; set; }
        public Nullable<int> Question5 { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Training Training { get; set; }
    }
}
